version: 0.2

phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform-"${TF_VERSION}"
      - echo "running terraform"
  pre_build:
    commands:
      - terraform init
        -backend-config="bucket=${TFSTATE_BUCKET}"
        -backend-config="key=${TFSTATE_KEY}"
        -backend-config="region=${REGION}"
  build:
    commands:
      - echo "Running Terraform"
      - if [ "${TF_ACTION}" = "plan" ]; then terraform plan -var-file=variables.tfvars; fi 
      - if [ "${TF_ACTION}" = "apply" ]; then terraform apply -var-file=variables.tfvars -auto-approve -no-color; fi 

  post_build:
    commands:
      - echo "Terraform Job completed"
